from web3 import Web3, HTTPProvider
from ens import ENS
infura_provider = HTTPProvider('https://ropsten.infura.io')
w3 = Web3(infura_provider)
# print(w3.sha3(text = 'nikhil').hex())
# print(w3.isConnected())
ens = ENS.fromWeb3(w3)
print(ens.namehash('transcripts.test').hex())
# print(ens.is_valid_name('transcripts.test'))
# ensAbi = [{"constant": True,"inputs":[{"name":"node","type":"bytes32"}],"name":"resolver","outputs":[{"name":"","type":"address"}],"payable":S,"type":"function"},{"constant":True,"inputs":[{"name":"node","type":"bytes32"}],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"node","type":"bytes32"},{"name":"label","type":"bytes32"},{"name":"owner","type":"address"}],"name":"setSubnodeOwner","outputs":[],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"node","type":"bytes32"},{"name":"ttl","type":"uint64"}],"name":"setTTL","outputs":[],"payable":False,"type":"function"},{"constant":True,"inputs":[{"name":"node","type":"bytes32"}],"name":"ttl","outputs":[{"name":"","type":"uint64"}],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"node","type":"bytes32"},{"name":"resolver","type":"address"}],"name":"setResolver","outputs":[],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"node","type":"bytes32"},{"name":"owner","type":"address"}],"name":"setOwner","outputs":[],"payable":False,"type":"function"},{"anonymous":False,"inputs":[{"indexed":True,"name":"node","type":"bytes32"},{"indexed":False,"name":"owner","type":"address"}],"name":"Transfer","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"node","type":"bytes32"},{"indexed":True,"name":"label","type":"bytes32"},{"indexed":False,"name":"owner","type":"address"}],"name":"NewOwner","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"node","type":"bytes32"},{"indexed":False,"name":"resolver","type":"address"}],"name":"NewResolver","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"node","type":"bytes32"},{"indexed":False,"name":"ttl","type":"uint64"}],"name":"NewTTL","type":"event"}]
# registrarAbi = [{"constant":True,"inputs":[],"name":"ens","outputs":[{"name":"","type":"address"}],"payable":False,"type":"function"},{"constant":True,"inputs":[{"name":"","type":"bytes32"}],"name":"expiryTimes","outputs":[{"name":"","type":"uint256"}],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"subnode","type":"bytes32"},{"name":"owner","type":"address"}],"name":"register","outputs":[],"payable":False,"type":"function"},{"constant":True,"inputs":[],"name":"rootNode","outputs":[{"name":"","type":"bytes32"}],"payable":False,"type":"function"},{"inputs":[{"name":"ensAddr","type":"address"},{"name":"node","type":"bytes32"}],"type":"constructor"}]
